common: &common
  VOTER_SEARCH_URL: https://vpa.wi.gov/VoterSearchScreen.aspx
  ADDRESS_SEARCH_URL: https://vpa.wi.gov/AddressSearchScreen.aspx
  
development:
  TWILIO_CALLER_ID: (414) 939-8633
  <<: *common

test:
  TWILIO_CALLER_ID: (414) 939-8633
  <<: *common
  
staging:
  TWILIO_CALLER_ID: (414) 939-8633
  <<: *common

production:
  TWILIO_CALLER_ID: (414) 263-9294
  <<: *common
